# ./docker-compose.yaml
version: '3.8'

services:
  java17:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: java17_container
    volumes:
      - ./host_directory:/container_directory/host_directory
    working_dir: /container_directory/host_directory
